

models:
  - name: gpt-4o-mini
    use: langchain_openai:ChatOpenAI
    model: gpt-4o-mini
    api_key: $OPENAI_API_KEY
    temperature: 0.7
    max_tokens: 6378
    # supports_thinking: true
    # when_thinking_enabled:
    #   temperature: 0.3
    #   max_tokens: 1024


sandbox:
  use: src.sandbox.local:LocalSandboxProvider

skills:
  container_path: /mnt/skills